POST http://localhost:8080/api/v1/authentication
Content-Type: application/json

{
    "password": "password",
    "email": "doctor@email.com"
}

> {%
    client.global.set("token", response.body);   // save token globally
%}

###
GET http://localhost:8080/api/v1/messages/unread
Authorization: Bearer {{token}}
###

GET http://localhost:8080/api/v1/chat/requests
Authorization: Bearer {{token}}
###